using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class DB_EnemyData : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_EnemyData(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_EnemyData(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4955536541876649653UL,10350697397875803273UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String uniqueKey
	{
		get => _uniqueKey[Index];
		set => _uniqueKey[Index] = value;
	}
	public System.String modelUniqueKey
	{
		get => _modelUniqueKey[Index];
		set => _modelUniqueKey[Index] = value;
	}
	public System.Single atk
	{
		get => _atk[Index];
		set => _atk[Index] = value;
	}
	public System.Int32 hp
	{
		get => _hp[Index];
		set => _hp[Index] = value;
	}
	public System.Single def
	{
		get => _def[Index];
		set => _def[Index] = value;
	}
	public System.Single spdef
	{
		get => _spdef[Index];
		set => _spdef[Index] = value;
	}
	public System.Single attackSpeed
	{
		get => _attackSpeed[Index];
		set => _attackSpeed[Index] = value;
	}
	public System.Single propertyReinforcePower
	{
		get => _propertyReinforcePower[Index];
		set => _propertyReinforcePower[Index] = value;
	}
	public System.Single propertyResistPower
	{
		get => _propertyResistPower[Index];
		set => _propertyResistPower[Index] = value;
	}
	public System.Int32 propertyState
	{
		get => _propertyState[Index];
		set => _propertyState[Index] = value;
	}
	public System.Int32 damageType
	{
		get => _damageType[Index];
		set => _damageType[Index] = value;
	}
	public System.Int32 unitType
	{
		get => _unitType[Index];
		set => _unitType[Index] = value;
	}
	public System.Single moveSpeed
	{
		get => _moveSpeed[Index];
		set => _moveSpeed[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5605900727010448709UL, 3787759488153421470UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_uniqueKey;
	public static BansheeGz.BGDatabase.BGFieldString _uniqueKey => _ufle12jhs77_uniqueKey ?? (_ufle12jhs77_uniqueKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5486584841661015506UL, 12724692272215307195UL), () => _ufle12jhs77_uniqueKey = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_modelUniqueKey;
	public static BansheeGz.BGDatabase.BGFieldString _modelUniqueKey => _ufle12jhs77_modelUniqueKey ?? (_ufle12jhs77_modelUniqueKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5524714954711315365UL, 4778198609947570870UL), () => _ufle12jhs77_modelUniqueKey = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_atk;
	public static BansheeGz.BGDatabase.BGFieldFloat _atk => _ufle12jhs77_atk ?? (_ufle12jhs77_atk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5396623800190823907UL, 13429253907522549162UL), () => _ufle12jhs77_atk = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
	public static BansheeGz.BGDatabase.BGFieldInt _hp => _ufle12jhs77_hp ?? (_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5757909049182982425UL, 12270368329764524969UL), () => _ufle12jhs77_hp = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_def;
	public static BansheeGz.BGDatabase.BGFieldFloat _def => _ufle12jhs77_def ?? (_ufle12jhs77_def = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4801246206359465427UL, 13618798402205468824UL), () => _ufle12jhs77_def = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_spdef;
	public static BansheeGz.BGDatabase.BGFieldFloat _spdef => _ufle12jhs77_spdef ?? (_ufle12jhs77_spdef = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4654686331147153500UL, 2837872386187590806UL), () => _ufle12jhs77_spdef = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_attackSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _attackSpeed => _ufle12jhs77_attackSpeed ?? (_ufle12jhs77_attackSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5283237450403178420UL, 14172208777497921671UL), () => _ufle12jhs77_attackSpeed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_propertyReinforcePower;
	public static BansheeGz.BGDatabase.BGFieldFloat _propertyReinforcePower => _ufle12jhs77_propertyReinforcePower ?? (_ufle12jhs77_propertyReinforcePower = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4679697312434670283UL, 2365062557594840505UL), () => _ufle12jhs77_propertyReinforcePower = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_propertyResistPower;
	public static BansheeGz.BGDatabase.BGFieldFloat _propertyResistPower => _ufle12jhs77_propertyResistPower ?? (_ufle12jhs77_propertyResistPower = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4829432456652747363UL, 6484324445973017273UL), () => _ufle12jhs77_propertyResistPower = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_propertyState;
	public static BansheeGz.BGDatabase.BGFieldInt _propertyState => _ufle12jhs77_propertyState ?? (_ufle12jhs77_propertyState = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4962329106411589224UL, 17090313909321595570UL), () => _ufle12jhs77_propertyState = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_damageType;
	public static BansheeGz.BGDatabase.BGFieldInt _damageType => _ufle12jhs77_damageType ?? (_ufle12jhs77_damageType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5128066249638100564UL, 14153476527045546128UL), () => _ufle12jhs77_damageType = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_unitType;
	public static BansheeGz.BGDatabase.BGFieldInt _unitType => _ufle12jhs77_unitType ?? (_ufle12jhs77_unitType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4640297914052036150UL, 13930597463506407045UL), () => _ufle12jhs77_unitType = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_moveSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _moveSpeed => _ufle12jhs77_moveSpeed ?? (_ufle12jhs77_moveSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5005368329512861673UL, 12986666523031679388UL), () => _ufle12jhs77_moveSpeed = null));
	private static readonly DB_EnemyData.Factory _factory0_PFS = new DB_EnemyData.Factory();
	private static readonly DB_TowerData.Factory _factory1_PFS = new DB_TowerData.Factory();
	private static readonly DB_HeroData.Factory _factory2_PFS = new DB_HeroData.Factory();
	private DB_EnemyData() : base(MetaDefault) {}
	private DB_EnemyData(BGId id) : base(MetaDefault, id) {}
	private DB_EnemyData(BGMetaEntity meta) : base(meta) {}
	private DB_EnemyData(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_EnemyData FindEntity(Predicate<DB_EnemyData> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_EnemyData> FindEntities(Predicate<DB_EnemyData> filter, List<DB_EnemyData> result=null, Comparison<DB_EnemyData> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_EnemyData> action, Predicate<DB_EnemyData> filter=null, Comparison<DB_EnemyData> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_EnemyData GetEntity(BGId entityId) => (DB_EnemyData) MetaDefault.GetEntity(entityId);
	public static DB_EnemyData GetEntity(int index) => (DB_EnemyData) MetaDefault[index];
	public static DB_EnemyData GetEntity(string entityName) => (DB_EnemyData) MetaDefault.GetEntity(entityName);
	public static DB_EnemyData NewEntity() => (DB_EnemyData) MetaDefault.NewEntity();
	public static DB_EnemyData NewEntity(BGId entityId) => (DB_EnemyData) MetaDefault.NewEntity(entityId);
	public static DB_EnemyData NewEntity(Action<DB_EnemyData> callback) => (DB_EnemyData) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_EnemyData)entity)));
}

public partial class DB_TowerData : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_TowerData(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_TowerData(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5560294284324679128UL,12164647786920778396UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String uniqueKey
	{
		get => _uniqueKey[Index];
		set => _uniqueKey[Index] = value;
	}
	public System.String modelUniqueKey
	{
		get => _modelUniqueKey[Index];
		set => _modelUniqueKey[Index] = value;
	}
	public System.Single atk
	{
		get => _atk[Index];
		set => _atk[Index] = value;
	}
	public System.Int32 hp
	{
		get => _hp[Index];
		set => _hp[Index] = value;
	}
	public System.Single def
	{
		get => _def[Index];
		set => _def[Index] = value;
	}
	public System.Single spdef
	{
		get => _spdef[Index];
		set => _spdef[Index] = value;
	}
	public System.Single attackSpeed
	{
		get => _attackSpeed[Index];
		set => _attackSpeed[Index] = value;
	}
	public System.Single propertyReinforcePower
	{
		get => _propertyReinforcePower[Index];
		set => _propertyReinforcePower[Index] = value;
	}
	public System.Single propertyResistPower
	{
		get => _propertyResistPower[Index];
		set => _propertyResistPower[Index] = value;
	}
	public System.Int32 propertyState
	{
		get => _propertyState[Index];
		set => _propertyState[Index] = value;
	}
	public System.Int32 damageType
	{
		get => _damageType[Index];
		set => _damageType[Index] = value;
	}
	public System.Int32 unitType
	{
		get => _unitType[Index];
		set => _unitType[Index] = value;
	}
	public System.Int32 critical
	{
		get => _critical[Index];
		set => _critical[Index] = value;
	}
	public System.Int32 criticalDamage
	{
		get => _criticalDamage[Index];
		set => _criticalDamage[Index] = value;
	}
	public System.Int32 lifeBloodAbsorption
	{
		get => _lifeBloodAbsorption[Index];
		set => _lifeBloodAbsorption[Index] = value;
	}
	public System.String skillUniqueKey
	{
		get => _skillUniqueKey[Index];
		set => _skillUniqueKey[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4941108061083073772UL, 6017762372021851288UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_uniqueKey;
	public static BansheeGz.BGDatabase.BGFieldString _uniqueKey => _ufle12jhs77_uniqueKey ?? (_ufle12jhs77_uniqueKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4828490049767187860UL, 13100746407448126643UL), () => _ufle12jhs77_uniqueKey = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_modelUniqueKey;
	public static BansheeGz.BGDatabase.BGFieldString _modelUniqueKey => _ufle12jhs77_modelUniqueKey ?? (_ufle12jhs77_modelUniqueKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5568638574695843986UL, 11297087621485972100UL), () => _ufle12jhs77_modelUniqueKey = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_atk;
	public static BansheeGz.BGDatabase.BGFieldFloat _atk => _ufle12jhs77_atk ?? (_ufle12jhs77_atk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4909830404343411534UL, 14754681351723998387UL), () => _ufle12jhs77_atk = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
	public static BansheeGz.BGDatabase.BGFieldInt _hp => _ufle12jhs77_hp ?? (_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4825319347893016138UL, 9600914690556261006UL), () => _ufle12jhs77_hp = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_def;
	public static BansheeGz.BGDatabase.BGFieldFloat _def => _ufle12jhs77_def ?? (_ufle12jhs77_def = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5208828385173780613UL, 12315020573164932739UL), () => _ufle12jhs77_def = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_spdef;
	public static BansheeGz.BGDatabase.BGFieldFloat _spdef => _ufle12jhs77_spdef ?? (_ufle12jhs77_spdef = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4809097609510087028UL, 3869444979217944500UL), () => _ufle12jhs77_spdef = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_attackSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _attackSpeed => _ufle12jhs77_attackSpeed ?? (_ufle12jhs77_attackSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5409438387876333748UL, 6891088894549973902UL), () => _ufle12jhs77_attackSpeed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_propertyReinforcePower;
	public static BansheeGz.BGDatabase.BGFieldFloat _propertyReinforcePower => _ufle12jhs77_propertyReinforcePower ?? (_ufle12jhs77_propertyReinforcePower = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5201509573395865833UL, 14929759093742407072UL), () => _ufle12jhs77_propertyReinforcePower = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_propertyResistPower;
	public static BansheeGz.BGDatabase.BGFieldFloat _propertyResistPower => _ufle12jhs77_propertyResistPower ?? (_ufle12jhs77_propertyResistPower = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4754163384060404509UL, 5301017864747725482UL), () => _ufle12jhs77_propertyResistPower = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_propertyState;
	public static BansheeGz.BGDatabase.BGFieldInt _propertyState => _ufle12jhs77_propertyState ?? (_ufle12jhs77_propertyState = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5402496191556378243UL, 10024595714572684455UL), () => _ufle12jhs77_propertyState = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_damageType;
	public static BansheeGz.BGDatabase.BGFieldInt _damageType => _ufle12jhs77_damageType ?? (_ufle12jhs77_damageType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5676910790904751021UL, 5153086813139453569UL), () => _ufle12jhs77_damageType = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_unitType;
	public static BansheeGz.BGDatabase.BGFieldInt _unitType => _ufle12jhs77_unitType ?? (_ufle12jhs77_unitType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5409446417320340000UL, 15792562398279814273UL), () => _ufle12jhs77_unitType = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_critical;
	public static BansheeGz.BGDatabase.BGFieldInt _critical => _ufle12jhs77_critical ?? (_ufle12jhs77_critical = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4720049083284349323UL, 2690949299795753351UL), () => _ufle12jhs77_critical = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_criticalDamage;
	public static BansheeGz.BGDatabase.BGFieldInt _criticalDamage => _ufle12jhs77_criticalDamage ?? (_ufle12jhs77_criticalDamage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4875561767774091098UL, 12530292192060871834UL), () => _ufle12jhs77_criticalDamage = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_lifeBloodAbsorption;
	public static BansheeGz.BGDatabase.BGFieldInt _lifeBloodAbsorption => _ufle12jhs77_lifeBloodAbsorption ?? (_ufle12jhs77_lifeBloodAbsorption = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4874692608475918203UL, 16951523883899290504UL), () => _ufle12jhs77_lifeBloodAbsorption = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_skillUniqueKey;
	public static BansheeGz.BGDatabase.BGFieldString _skillUniqueKey => _ufle12jhs77_skillUniqueKey ?? (_ufle12jhs77_skillUniqueKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5563077167881212240UL, 11781104253017428148UL), () => _ufle12jhs77_skillUniqueKey = null));
	private static readonly DB_EnemyData.Factory _factory0_PFS = new DB_EnemyData.Factory();
	private static readonly DB_TowerData.Factory _factory1_PFS = new DB_TowerData.Factory();
	private static readonly DB_HeroData.Factory _factory2_PFS = new DB_HeroData.Factory();
	private DB_TowerData() : base(MetaDefault) {}
	private DB_TowerData(BGId id) : base(MetaDefault, id) {}
	private DB_TowerData(BGMetaEntity meta) : base(meta) {}
	private DB_TowerData(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_TowerData FindEntity(Predicate<DB_TowerData> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_TowerData> FindEntities(Predicate<DB_TowerData> filter, List<DB_TowerData> result=null, Comparison<DB_TowerData> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_TowerData> action, Predicate<DB_TowerData> filter=null, Comparison<DB_TowerData> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_TowerData GetEntity(BGId entityId) => (DB_TowerData) MetaDefault.GetEntity(entityId);
	public static DB_TowerData GetEntity(int index) => (DB_TowerData) MetaDefault[index];
	public static DB_TowerData GetEntity(string entityName) => (DB_TowerData) MetaDefault.GetEntity(entityName);
	public static DB_TowerData NewEntity() => (DB_TowerData) MetaDefault.NewEntity();
	public static DB_TowerData NewEntity(BGId entityId) => (DB_TowerData) MetaDefault.NewEntity(entityId);
	public static DB_TowerData NewEntity(Action<DB_TowerData> callback) => (DB_TowerData) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_TowerData)entity)));
}

public partial class DB_HeroData : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_HeroData(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_HeroData(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4944539683525512374UL,5739453475281730984UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String uniqueKey
	{
		get => _uniqueKey[Index];
		set => _uniqueKey[Index] = value;
	}
	public System.String modelUniqueKey
	{
		get => _modelUniqueKey[Index];
		set => _modelUniqueKey[Index] = value;
	}
	public System.Single atk
	{
		get => _atk[Index];
		set => _atk[Index] = value;
	}
	public System.Int32 hp
	{
		get => _hp[Index];
		set => _hp[Index] = value;
	}
	public System.Single def
	{
		get => _def[Index];
		set => _def[Index] = value;
	}
	public System.Single spdef
	{
		get => _spdef[Index];
		set => _spdef[Index] = value;
	}
	public System.Single attackSpeed
	{
		get => _attackSpeed[Index];
		set => _attackSpeed[Index] = value;
	}
	public System.Single propertyReinforcePower
	{
		get => _propertyReinforcePower[Index];
		set => _propertyReinforcePower[Index] = value;
	}
	public System.Single propertyResistPower
	{
		get => _propertyResistPower[Index];
		set => _propertyResistPower[Index] = value;
	}
	public System.Int32 propertyState
	{
		get => _propertyState[Index];
		set => _propertyState[Index] = value;
	}
	public System.Int32 damageType
	{
		get => _damageType[Index];
		set => _damageType[Index] = value;
	}
	public System.Int32 unitType
	{
		get => _unitType[Index];
		set => _unitType[Index] = value;
	}
	public System.Int32 critical
	{
		get => _critical[Index];
		set => _critical[Index] = value;
	}
	public System.Int32 criticalDamage
	{
		get => _criticalDamage[Index];
		set => _criticalDamage[Index] = value;
	}
	public System.Int32 lifeBloodAbsorption
	{
		get => _lifeBloodAbsorption[Index];
		set => _lifeBloodAbsorption[Index] = value;
	}
	public System.String skillUniqueKeys
	{
		get => _skillUniqueKeys[Index];
		set => _skillUniqueKeys[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4935204605815414357UL, 14203226851579194013UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_uniqueKey;
	public static BansheeGz.BGDatabase.BGFieldString _uniqueKey => _ufle12jhs77_uniqueKey ?? (_ufle12jhs77_uniqueKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5439179755775953358UL, 10732270685346369166UL), () => _ufle12jhs77_uniqueKey = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_modelUniqueKey;
	public static BansheeGz.BGDatabase.BGFieldString _modelUniqueKey => _ufle12jhs77_modelUniqueKey ?? (_ufle12jhs77_modelUniqueKey = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5464261943357582103UL, 14683487545478790051UL), () => _ufle12jhs77_modelUniqueKey = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_atk;
	public static BansheeGz.BGDatabase.BGFieldFloat _atk => _ufle12jhs77_atk ?? (_ufle12jhs77_atk = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5338260521116776823UL, 14898268849904829604UL), () => _ufle12jhs77_atk = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_hp;
	public static BansheeGz.BGDatabase.BGFieldInt _hp => _ufle12jhs77_hp ?? (_ufle12jhs77_hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5410141584566223455UL, 13175938457208933788UL), () => _ufle12jhs77_hp = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_def;
	public static BansheeGz.BGDatabase.BGFieldFloat _def => _ufle12jhs77_def ?? (_ufle12jhs77_def = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5480041411568293083UL, 10764454980208335745UL), () => _ufle12jhs77_def = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_spdef;
	public static BansheeGz.BGDatabase.BGFieldFloat _spdef => _ufle12jhs77_spdef ?? (_ufle12jhs77_spdef = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5155850278107794977UL, 4390348951537723282UL), () => _ufle12jhs77_spdef = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_attackSpeed;
	public static BansheeGz.BGDatabase.BGFieldFloat _attackSpeed => _ufle12jhs77_attackSpeed ?? (_ufle12jhs77_attackSpeed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4806443368126536485UL, 14039356821874969751UL), () => _ufle12jhs77_attackSpeed = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_propertyReinforcePower;
	public static BansheeGz.BGDatabase.BGFieldFloat _propertyReinforcePower => _ufle12jhs77_propertyReinforcePower ?? (_ufle12jhs77_propertyReinforcePower = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5400108535498627408UL, 17068153071783811480UL), () => _ufle12jhs77_propertyReinforcePower = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_propertyResistPower;
	public static BansheeGz.BGDatabase.BGFieldFloat _propertyResistPower => _ufle12jhs77_propertyResistPower ?? (_ufle12jhs77_propertyResistPower = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5716331577956536733UL, 16786679276793332619UL), () => _ufle12jhs77_propertyResistPower = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_propertyState;
	public static BansheeGz.BGDatabase.BGFieldInt _propertyState => _ufle12jhs77_propertyState ?? (_ufle12jhs77_propertyState = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5316587393862505442UL, 8021622467166588851UL), () => _ufle12jhs77_propertyState = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_damageType;
	public static BansheeGz.BGDatabase.BGFieldInt _damageType => _ufle12jhs77_damageType ?? (_ufle12jhs77_damageType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5122176571119634641UL, 12209163275397784251UL), () => _ufle12jhs77_damageType = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_unitType;
	public static BansheeGz.BGDatabase.BGFieldInt _unitType => _ufle12jhs77_unitType ?? (_ufle12jhs77_unitType = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5485082440525957567UL, 10567072265464693649UL), () => _ufle12jhs77_unitType = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_critical;
	public static BansheeGz.BGDatabase.BGFieldInt _critical => _ufle12jhs77_critical ?? (_ufle12jhs77_critical = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5132095929583390287UL, 2348104840047443872UL), () => _ufle12jhs77_critical = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_criticalDamage;
	public static BansheeGz.BGDatabase.BGFieldInt _criticalDamage => _ufle12jhs77_criticalDamage ?? (_ufle12jhs77_criticalDamage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5643355240828654831UL, 5261328214393971090UL), () => _ufle12jhs77_criticalDamage = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_lifeBloodAbsorption;
	public static BansheeGz.BGDatabase.BGFieldInt _lifeBloodAbsorption => _ufle12jhs77_lifeBloodAbsorption ?? (_ufle12jhs77_lifeBloodAbsorption = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4962294969390550658UL, 15230492131813120677UL), () => _ufle12jhs77_lifeBloodAbsorption = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_skillUniqueKeys;
	public static BansheeGz.BGDatabase.BGFieldString _skillUniqueKeys => _ufle12jhs77_skillUniqueKeys ?? (_ufle12jhs77_skillUniqueKeys = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4903934387925721988UL, 5166175781583776177UL), () => _ufle12jhs77_skillUniqueKeys = null));
	private static readonly DB_EnemyData.Factory _factory0_PFS = new DB_EnemyData.Factory();
	private static readonly DB_TowerData.Factory _factory1_PFS = new DB_TowerData.Factory();
	private static readonly DB_HeroData.Factory _factory2_PFS = new DB_HeroData.Factory();
	private DB_HeroData() : base(MetaDefault) {}
	private DB_HeroData(BGId id) : base(MetaDefault, id) {}
	private DB_HeroData(BGMetaEntity meta) : base(meta) {}
	private DB_HeroData(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_HeroData FindEntity(Predicate<DB_HeroData> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_HeroData> FindEntities(Predicate<DB_HeroData> filter, List<DB_HeroData> result=null, Comparison<DB_HeroData> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_HeroData> action, Predicate<DB_HeroData> filter=null, Comparison<DB_HeroData> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_HeroData GetEntity(BGId entityId) => (DB_HeroData) MetaDefault.GetEntity(entityId);
	public static DB_HeroData GetEntity(int index) => (DB_HeroData) MetaDefault[index];
	public static DB_HeroData GetEntity(string entityName) => (DB_HeroData) MetaDefault.GetEntity(entityName);
	public static DB_HeroData NewEntity() => (DB_HeroData) MetaDefault.NewEntity();
	public static DB_HeroData NewEntity(BGId entityId) => (DB_HeroData) MetaDefault.NewEntity(entityId);
	public static DB_HeroData NewEntity(Action<DB_HeroData> callback) => (DB_HeroData) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_HeroData)entity)));
}
#pragma warning restore 414
